adapter:
  type: generic
  quantize_first_layer: false
  quantized_ops: ["-1"]
  input_quantization: true
  quantization_type: fp8_e4m3

quantization:
  format: fp8_e4m3
  bias: 7
  calib_method: max

dataset:
  name: imagenet
  path: tests/data/imagenette2-320/val
  batch_size: 2
  num_workers: 0

evaluation:
  mode: compare
  compare_batches: 1
